### PR TITLE
Lcg/rspec3

### PR DESCRIPTION
**Pull request by lamont-granquist**
- bumps all the gems.
- bundle will install now on ubuntu 14.04
- rspec updated to rspec 3 and syntax fixed to expect

### CODE REVIEW

**Comment by lamont-granquist** [comment]
part #1 of today's rage coding.

@chef/release-engineers @jdmundrawala review

**Comment by jdmundrawala** [comment]
working on the review, but can we add travis?

**Comment by lamont-granquist** [comment]
yes that would be part #2

**Comment by jdmundrawala** [comment]
:+1:

**Comment by jdmundrawala** [comment]
also, `be_false` vs `be false`...thank you. That was tripping me up today. Ended up going with `eq`

**Comment by yzl** [comment]
:+1:

**Comment by lamont-granquist** [comment]
It actually found a ton of bad code that should really be cleaned up in theory.  All the be_falsey stuff coming back from `?` methods are buggy things.

**Pull request merged**
