### PR TITLE
this might fix cumulus distro

### PR DESCRIPTION
**Pull request by lamont-granquist**

### CODE REVIEW

**Comment by lamont-granquist** [comment]
@chef/client-core @chef/client-engineers there's no good way to test this short of merging, pushing to preprod and having the user who reported it try it out.

**Comment by danielsdeleo** [comment]
Go for it :+1:

**Comment by beddari** [comment]
Depending on the hardware platform Cumulus arch is x86_64 or PowerPC. So you'd need to confine this ...

**Comment by lamont-granquist** [comment]
No, install.sh has a mini-ohai in it, so it'll just never report a 32-bit arch on cumulus linux, and since we don't build powerpc for anything yet it'll just error out there with a 404 (which is correct, it doesn't exist).

**Comment by beddari** [comment]
Ah ... thanks for the explanation :+1:

**Pull request merged**
