### PR TITLE
route for install.ps1

### PR DESCRIPTION
**Pull request by smurawski**
@jaym This should add the route for /install.ps1 that was missing.

### CODE REVIEW

**Comment by jaym** [comment]
:+1:

**Comment by smurawski** [comment]
@lamont-granquist @danielsdeleo @schisamo Can I get another :+1: on adding a route for install.ps1?

**Comment by lamont-granquist** [comment]
yep :+1:

**Comment by smurawski** [comment]
Thanks @lamont-granquist !

**Pull request merged**
