### PR TITLE
add big warning

### PR DESCRIPTION
**Pull request by lamont-granquist**
people need to not use latest

### CODE REVIEW

**Comment by lamont-granquist** [comment]
@chef/client-engineers @chef/client-core

**Comment by danielsdeleo** [comment]
I kinda wonder if this is actually something we'll end up encouraging people to do when we get to CD nirvana. But we are not at CD nirvana now, so :+1:

**Comment by danielsdeleo** [comment]
Though one concern I have is that this is the default way we tell people to install and it results in a warning. Should we make a docs pass to add `-v 12` to the install instructions?

**Comment by lamont-granquist** [comment]
I'd vote we change the docs and the website, yes.   After getting burned with chef 11 and chef 12, I think this is the right thing to do.

Paging @jamescott

**Comment by tyler-ball** [comment]
:+1: to the warning and the suggested doc change

**Pull request merged**
